//------------------------------------------------------------------------------
//  TransactionType.cs
//
//  Implementation of: TransactionType (Enumeration) <<enumeration>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:11
//  Original author: Miguel
//------------------------------------------------------------------------------

namespace DFlow.Budget.Core.Model
{
    public enum TransactionType
    {
        Income,
        Expense,
        Loan,
        Savings,
        Investment,
        Tax
    }
}
